package com.trustrent.backend.enums;

public enum TrustEventType {
    RENT_PAID_EARLY, RENT_PAID_ON_TIME, RENT_PAID_LATE, RENT_MISSED,
    RENTAL_COMPLETED, POSITIVE_REVIEW, NEGATIVE_REVIEW,
    PROPERTY_CARE_POSITIVE, PROPERTY_CARE_NEGATIVE,
    COMPLIANCE_POSITIVE, COMPLIANCE_NEGATIVE,
    VERIFIED_COMPLAINT, COMPLAINT_RESOLVED
}
